import { useEffect, useState } from 'react'
import { apiRequest, getCachedSession } from './platform-api'
import AdminOperations from './AdminOperations'
import './admin.css'

export default function AdminView() {
  const [overview,setOverview]=useState(null); const [users,setUsers]=useState([]); const [orders,setOrders]=useState([]); const [rules,setRules]=useState([]); const [error,setError]=useState(''); const user=getCachedSession()?.user
  useEffect(()=>{if(!user)return window.location.assign('/?acceso=login');Promise.all([apiRequest('/admin/overview'),apiRequest('/admin/users'),apiRequest('/admin/orders'),apiRequest('/admin/rules')]).then(([o,u,or,r])=>{setOverview(o.overview);setUsers(u.users);setOrders(or.orders);setRules(r.rules)}).catch(e=>setError(e.message))},[])
  if(error)return <main className="admin-shell"><header><a href="/">chatenlugar</a></header><section className="admin-state"><h1>Administración restringida</h1><p>{error}</p><a href="/">Volver al inicio</a></section></main>
  return <main className="admin-shell"><header><a href="/">chatenlugar</a><nav><a href="/campanias">Campañas</a><a href="/tienda">Tienda</a><a href="/perfil">Mi perfil</a></nav></header><section className="admin-hero"><p>ADMINISTRACIÓN</p><h1>Operación de la plataforma.</h1><span>Las reglas de comisiones, pujas y ganancias permanecen inactivas hasta contar con una definición comercial aprobada.</span></section><section className="admin-content">{!overview?<p className="admin-state">Cargando información administrativa.</p>:<><div className="admin-stats">{Object.entries(overview).map(([key,value])=><article key={key}><span>{key.replaceAll('_',' ')}</span><strong>{value}</strong></article>)}</div><div className="admin-grid"><section><h2>Usuarios</h2>{users.map(x=><div key={x.id}><strong>{x.name}</strong><span>@{x.handle} · {x.role}</span></div>)}</section><section><h2>Pedidos</h2>{orders.map(x=><div key={x.id}><strong>{x.customer_name}</strong><span>{x.status}</span></div>)}</section><section><h2>Reglas comerciales</h2>{rules.length?rules.map(x=><div key={x.key}><strong>{x.key}</strong><span>{x.is_active?'Activa':'Inactiva'}</span></div>):<p>Sin reglas activas.</p>}</section></div><AdminOperations /></>}</section></main>
}
